version: 0.2

phases:
  build:
    commands:
      - aws s3 sync . s3://csce412leenser.me --exclude ".git/*" --exclude "index.html"
      - aws s3 cp index.html s3://csce412leenser.me/index.html --content-type text/html